- name: Ensure required packages are installed
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - curl
      - gpg
    state: present
- name: Create an empty file for the containerd module
  ansible.builtin.copy:
    content: ""
    dest: /etc/modules-load.d/containerd.conf
    force: false
    mode: "0644"

- name: Configure modules for containerd
  ansible.builtin.blockinfile:
    path: /etc/modules-load.d/containerd.conf
    block: |
      overlay
      br_netfilter

- name: Add Docker APT GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu xenial stable
    state: present
    filename: "docker"

- name: Run apt-get update and install docker packages
  ansible.builtin.apt:
    update_cache: true
    name:
      - containerd.io
  become: true
