---
- name: Install Docker for Debian family
  when:
    - ansible_os_family == "Debian"
  ansible.builtin.include_tasks: debian.yml

- name: Install Docker for Arch Linux
  when:
    - ansible_os_family == "Archlinux"
  ansible.builtin.include_tasks: arch.yml

- name: Systemctl configuration
  ansible.builtin.include_tasks: systemd.yml

- name: Start and enable containerd
  ansible.builtin.systemd:
    name: containerd
    state: started
    enabled: true
