---
- name: Ensure /etc/containerd directory exists
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: "0755"

- name: Generate containerd default config and save to /etc/containerd/config.toml
  ansible.builtin.command: "containerd config default > /etc/containerd/config.toml"
  args:
    creates: /etc/containerd/config.toml

- name: Write containerd config to /etc/containerd/config.toml
  ansible.builtin.copy:
    content: "{{ containerd_config.stdout }}"
    dest: /etc/containerd/config.toml
    mode: "0644"

- name: Ensure containerd is enabled and started
  ansible.builtin.systemd:
    name: containerd
    enabled: true
    state: started
