---
- name: Ensure /etc/containerd directory exists
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: "0755"

- name: Ensure containerd is enabled and started
  ansible.builtin.systemd:
    name: containerd
    enabled: true
    state: started
